# This is a GitHub Actions workflow file.
# It automatically builds and deploys your FastAPI backend to Azure App Service.

name: Deploy Backend to Azure App Service

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Only run if files in the backend folder change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: 'Build and deploy container app to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'securevault-backend' 
        images: 'mcr.microsoft.com/appsvc/staticsite:latest' # Placeholder, the action builds from your Dockerfile
        
    - name: 'Logout of Azure'
      run: |
        az logout